name: grad-classifier
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy=2.4.1
  - pandas=2.3.3
  - scipy=1.16.3
  - scikit-learn=1.8.0
  - matplotlib=3.10.8
  - seaborn=0.13.2
  - openpyxl=3.1.5
  - pyyaml=6.0.2
